# Exploring Hacker News Posts

In this project, we'll compare two different types of posts from Hacker News, a popular site where technology related stories (or 'posts') are voted and commented upon. The two types of posts we'll explore begin with either Ask HN or Show HN.

Users submit Ask HN posts to ask the Hacker News community a specific question, such as "What is the best online course you've ever taken?" Likewise, users submit Show HN posts to show the Hacker News community a project, product, or just generally something interesting.

We'll specifically compare these two types of posts to determine the following:

Do Ask HN or Show HN receive more comments on average?
Do posts created at a certain time receive more comments on average?
It should be noted that the data set we're working with was reduced from almost 300,000 rows to approximately 20,000 rows by removing all submissions that did not receive any comments, and then randomly sampling from the remaining submissions.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('hacker_news.csv')

In [3]:
df.head()

,id,title,url,num_points,num_comments,author,created_at
0,12224879,Interactive Dynamic Video,http://www.interactivedynamicvideo.com/,386,52,ne0phyte,8/4/2016 11:52
1,10975351,How to Use Open Source and Shut the Fuck Up at...,http://hueniverse.com/2016/01/26/how-to-use-op...,39,10,josep2,1/26/2016 19:30
2,11964716,Florida DJs May Face Felony for April Fools' W...,http://www.thewire.com/entertainment/2013/04/f...,2,1,vezycash,6/23/2016 22:20
3,11919867,Technology ventures: From Idea to Enterprise,https://www.amazon.com/Technology-Ventures-Ent...,3,1,hswarna,6/17/2016 0:01
4,10301696,Note by Note: The Making of Steinway L1037 (2007),http://www.nytimes.com/2007/11/07/movies/07ste...,8,2,walterbell,9/30/2015 4:12

In [4]:
df.columns

Index(['id', 'title', 'url', 'num_points', 'num_comments', 'author',
       'created_at'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20100 entries, 0 to 20099
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            20100 non-null  int64
 1   title         20100 non-null  object
 2   url           17660 non-null  object
 3   num_points    20100 non-null  int64
 4   num_comments  20100 non-null  int64
 5   author        20100 non-null  object
 6   created_at    20100 non-null  object
dtypes: int64(3), object(4)
memory usage: 1.1+ MB

In [6]:
df['title'] = df['title'].str.lower()

In [7]:
df.created_at = pd.to_datetime(df['created_at'])

In [8]:
ask_posts = df[df.title.str.startswith('ask hn')]
show_posts = df[df.title.str.startswith('show hn')]
other_posts = df[~(df.title.str.startswith('ask hn') |
                   df.title.str.startswith('show hn'))]

In [9]:
ask_posts.shape[0] + show_posts.shape[0] + other_posts.shape[0], df.shape[0]

(20100, 20100)

In [10]:
total_ask_comments = ask_posts.num_comments.values.sum()
avg_ask_comments = total_ask_comments/ask_posts.shape[0]
avg_ask_comments

14.038417431192661

In [11]:
total_show_comments = show_posts.num_comments.values.sum()
avg_show_comments = total_show_comments/show_posts.shape[0]
avg_show_comments

10.31669535283993

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20100 entries, 0 to 20099
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            20100 non-null  int64
 1   title         20100 non-null  object
 2   url           17660 non-null  object
 3   num_points    20100 non-null  int64
 4   num_comments  20100 non-null  int64
 5   author        20100 non-null  object
 6   created_at    20100 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(3), object(3)
memory usage: 1.1+ MB

In [13]:
result_list = ask_posts[['created_at', 'num_comments']]
result_list.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1744 entries, 7 to 20061
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   created_at    1744 non-null   datetime64[ns]
 1   num_comments  1744 non-null   int64
dtypes: datetime64[ns](1), int64(1)
memory usage: 40.9 KB

In [14]:
counts_by_hour = {}
comments_by_hour = {}

In [15]:
result_list.head()

            created_at  num_comments
7  2016-08-16 09:55:00             6
17 2015-11-22 13:43:00            29
22 2016-05-02 10:14:00             1
30 2016-08-02 14:20:00             3
31 2015-10-15 16:38:00            17

In [16]:
hours = list(result_list.created_at.dt.hour.values)
num_comments = list(result_list.num_comments.values)

In [17]:
new_list = [list(x) for x in zip(hours, num_comments)]

In [18]:
new_list

[[9, 6],
 [13, 29],
 [10, 1],
 [14, 3],
 [16, 17],
 [23, 1],
 [12, 4],
 [9, 1],
 [17, 1],
 [17, 2],
 [17, 7],
 [13, 1],
 [15, 1],
 [21, 4],
 [21, 4],
 [20, 2],
 [2, 3],
 [12, 1],
 [2, 22],
 [14, 2],
 [18, 2],
 [13, 7],
 [16, 7],
 [17, 3],
 [15, 6],
 [14, 2],
 [3, 1],
 [21, 3],
 [5, 29],
 [3, 2],
 [21, 20],
 [19, 3],
 [18, 3],
 [1, 33],
 [9, 5],
 [1, 4],
 [13, 7],
 [17, 11],
 [19, 1],
 [15, 9],
 [14, 2],
 [20, 37],
 [16, 1],
 [22, 2],
 [23, 4],
 [19, 1],
 [1, 1],
 [17, 182],
 [19, 5],
 [16, 9],
 [22, 8],
 [1, 24],
 [8, 5],
 [4, 3],
 [20, 4],
 [12, 7],
 [0, 10],
 [14, 3],
 [10, 3],
 [16, 4],
 [21, 3],
 [17, 20],
 [10, 1],
 [16, 140],
 [13, 5],
 [13, 3],
 [2, 30],
 [16, 2],
 [19, 2],
 [14, 5],
 [14, 1],
 [14, 17],
 [6, 1],
 [17, 1],
 [23, 5],
 [18, 5],
 [5, 2],
 [17, 8],
 [20, 2],
 [18, 6],
 [14, 22],
 [2, 7],
 [20, 12],
 [0, 1],
 [23, 2],
 [15, 72],
 [17, 2],
 [8, 130],
 [16, 3],
 [3, 2],
 [19, 7],
 [18, 15],
 [7, 2],
 [19, 6],
 [17, 1],
 [12, 1],
 [16, 10],
 [14, 2],
 [2, 15],
 [8, 8],
 [21, 2],
 [14, 1],
 [23, 1],
 [15, 1],
 [18, 6],
 [1, 43],
 [22, 19],
 [14, 5],
 [21, 1],
 [19, 234],
 [17, 5],
 [18, 6],
 [16, 9],
 [14, 1],
 [6, 1],
 [10, 19],
 [7, 3],
 [18, 1],
 [21, 25],
 [18, 7],
 [21, 7],
 [10, 71],
 [19, 3],
 [16, 17],
 [15, 2],
 [15, 5],
 [11, 2],
 [0, 3],
 [0, 61],
 [18, 2],
 [12, 17],
 [5, 2],
 [19, 3],
 [16, 2],
 [0, 1],
 [3, 5],
 [21, 1],
 [19, 13],
 [10, 12],
 [10, 1],
 [14, 1],
 [19, 185],
 [23, 7],
 [15, 2],
 [22, 4],
 [11, 2],
 [20, 2],
 [14, 1],
 [13, 2],
 [6, 2],
 [21, 2],
 [21, 1],
 [10, 22],
 [4, 37],
 [11, 8],
 [15, 1],
 [13, 55],
 [22, 9],
 [12, 3],
 [18, 20],
 [16, 6],
 [15, 8],
 [6, 3],
 [12, 10],
 [3, 11],
 [2, 1],
 [2, 8],
 [0, 2],
 [12, 35],
 [14, 4],
 [17, 10],
 [22, 3],
 [12, 8],
 [19, 1],
 [17, 55],
 [16, 8],
 [11, 5],
 [15, 1],
 [18, 4],
 [13, 4],
 [19, 3],
 [22, 1],
 [19, 2],
 [18, 11],
 [10, 1],
 [8, 3],
 [1, 3],
 [13, 20],
 [19, 1],
 [6, 9],
 [17, 5],
 [15, 250],
 [22, 11],
 [15, 93],
 [19, 5],
 [12, 2],
 [1, 1],
 [20, 4],
 [8, 4],
 [16, 2],
 [16, 2],
 [13, 92],
 [11, 4],
 [16, 112],
 [4, 4],
 [13, 16],
 [0, 4],
 [1, 3],
 [12, 4],
 [2, 4],
 [2, 4],
 [21, 9],
 [18, 11],
 [0, 43],
 [22, 3],
 [7, 1],
 [19, 3],
 [16, 5],
 [8, 2],
 [22, 1],
 [4, 1],
 [10, 3],
 [15, 3],
 [8, 29],
 [7, 11],
 [14, 3],
 [15, 6],
 [15, 3],
 [4, 3],
 [13, 15],
 [23, 1],
 [21, 1],
 [7, 2],
 [13, 5],
 [17, 9],
 [3, 1],
 [19, 2],
 [21, 7],
 [4, 1],
 [21, 1],
 [19, 5],
 [14, 11],
 [16, 13],
 [15, 2],
 [23, 2],
 [21, 3],
 [15, 2],
 [20, 1],
 [16, 3],
 [19, 5],
 [8, 1],
 [17, 2],
 [0, 32],
 [18, 28],
 [17, 5],
 [23, 2],
 [23, 1],
 [4, 2],
 [6, 6],
 [14, 10],
 [19, 3],
 [21, 3],
 [7, 2],
 [20, 1],
 [16, 2],
 [8, 1],
 [5, 10],
 [21, 2],
 [23, 5],
 [18, 3],
 [20, 1],
 [15, 1],
 [16, 5],
 [9, 60],
 [0, 2],
 [17, 1],
 [8, 6],
 [17, 12],
 [15, 22],
 [18, 32],
 [17, 62],
 [13, 2],
 [20, 2],
 [3, 18],
 [18, 2],
 [19, 1],
 [10, 3],
 [2, 11],
 [19, 4],
 [2, 11],
 [13, 34],
 [5, 5],
 [18, 10],
 [23, 2],
 [15, 6],
 [12, 12],
 [19, 2],
 [8, 1],
 [5, 3],
 [11, 266],
 [20, 183],
 [12, 3],
 [21, 10],
 [16, 2],
 [19, 4],
 [18, 1],
 [4, 5],
 [20, 8],
 [18, 1],
 [13, 5],
 [21, 10],
 [15, 3],
 [4, 1],
 [15, 1],
 [17, 2],
 [13, 1],
 [15, 6],
 [22, 1],
 [15, 1],
 [14, 1],
 [18, 6],
 [4, 2],
 [15, 12],
 [5, 1],
 [16, 2],
 [18, 14],
 [17, 2],
 [22, 6],
 [13, 10],
 [1, 19],
 [20, 1],
 [22, 7],
 [2, 8],
 [13, 4],
 [11, 5],
 [4, 18],
 [18, 17],
 [10, 7],
 [20, 3],
 [14, 1],
 [5, 10],
 [17, 4],
 [11, 3],
 [21, 1],
 [3, 2],
 [16, 9],
 [11, 2],
 [14, 4],
 [20, 26],
 [14, 11],
 [3, 15],
 [6, 7],
 [19, 46],
 [6, 5],
 [17, 5],
 [15, 3],
 [7, 3],
 [3, 16],
 [12, 3],
 [0, 8],
 [13, 4],
 [8, 24],
 [11, 8],
 [11, 4],
 [8, 1],
 [12, 7],
 [15, 2],
 [11, 1],
 [11, 4],
 [22, 2],
 [5, 22],
 [9, 1],
 [3, 9],
 [14, 16],
 [11, 1],
 [12, 2],
 [22, 43],
 [18, 3],
 [19, 18],
 [18, 3],
 [1, 22],
 [8, 4],
 [12, 5],
 [16, 2],
 [20, 4],
 [1, 13],
 [19, 1],
 [17, 1],
 [17, 29],
 [12, 2],
 [2, 41],
 [14, 6],
 [14, 4],
 [18, 1],
 [14, 2],
 [13, 6],
 [15, 3],
 [15, 10],
 [21, 1],
 [18, 2],
 [5, 3],
 [21, 9],
 [3, 14],
 [15, 1],
 [9, 2],
 [20, 2],
 [12, 1],
 [15, 1],
 [18, 11],
 [18, 1],
 [1, 9],
 [22, 4],
 [14, 85],
 [15, 4],
 [9, 42],
 [15, 7],
 [22, 9],
 [0, 1],
 [11, 4],
 [18, 9],
 [10, 1],
 [22, 20],
 [11, 6],
 [23, 1],
 [22, 2],
 [15, 910],
 [22, 3],
 [12, 1],
 [10, 12],
 [4, 2],
 [1, 3],
 [19, 5],
 [2, 12],
 [0, 3],
 [17, 1],
 [13, 95],
 [2, 6],
 [3, 1],
 [13, 1],
 [15, 3],
 [0, 9],
 [18, 66],
 [21, 1],
 [14, 3],
 [23, 8],
 [20, 2],
 [17, 6],
 [21, 10],
 [21, 6],
 [3, 2],
 [22, 6],
 [6, 2],
 [4, 11],
 [15, 2],
 [0, 29],
 [14, 7],
 [14, 12],
 [14, 2],
 [11, 2],
 [20, 6],
 [16, 1],
 [6, 2],
 [18, 7],
 [10, 5],
 [22, 1],
 [5, 6],
 [1, 1],
 [11, 1],
 [16, 2],
 [14, 125],
 [4, 1],
 [15, 6],
 [21, 2],
 [2, 5],
 [8, 1],
 [13, 17],
 [22, 2],
 [14, 4],
 [3, 3],
 [22, 13],
 [3, 2],
 [17, 2],
 [16, 2],
 [15, 7],
 [6, 2],
 [21, 1],
 [20, 40],
 [19, 3],
 [5, 1],
 [16, 51],
 [19, 12],
 [11, 6],
 [16, 1],
 [14, 14],
 [6, 10],
 [20, 6],
 [8, 2],
 [17, 31],
 [22, 6],
 [18, 2],
 [15, 162],
 [18, 2],
 [17, 6],
 [20, 7],
 [19, 2],
 [10, 4],
 [6, 1],
 [19, 9],
 [23, 15],
 [0, 3],
 [1, 14],
 [23, 1],
 [17, 2],
 [15, 3],
 [6, 2],
 [23, 12],
 [4, 2],
 [16, 5],
 [22, 1],
 [2, 1],
 [1, 4],
 [21, 2],
 [12, 69],
 [22, 2],
 [6, 2],
 [22, 1],
 [10, 6],
 [17, 5],
 [23, 7],
 [18, 5],
 [21, 3],
 [9, 3],
 [14, 1],
 [0, 3],
 [17, 4],
 [2, 15],
 [10, 1],
 [6, 1],
 [11, 6],
 [18, 3],
 [15, 4],
 [21, 2],
 [2, 1],
 [22, 6],
 [13, 2],
 [16, 3],
 [16, 9],
 [5, 117],
 [17, 1],
 [21, 37],
 [4, 5],
 [11, 5],
 [21, 16],
 [7, 6],
 [17, 26],
 [20, 1],
 [19, 17],
 [10, 83],
 [16, 9],
 [0, 4],
 [16, 6],
 [17, 5],
 [3, 8],
 [14, 1],
 [12, 11],
 [19, 2],
 [18, 1],
 [10, 49],
 [2, 1],
 [3, 4],
 [15, 3],
 [15, 2],
 [1, 37],
 [17, 4],
 [2, 6],
 [15, 8],
 [1, 65],
 [12, 60],
 [0, 2],
 [10, 109],
 [16, 12],
 [22, 12],
 [18, 3],
 [8, 2],
 [15, 3],
 [19, 2],
 [21, 1],
 [14, 51],
 [13, 2],
 [8, 2],
 [14, 2],
 [18, 4],
 [10, 90],
 [19, 2],
 [0, 1],
 [15, 1],
 [19, 81],
 [14, 1],
 [20, 514],
 [14, 3],
 [5, 16],
 [6, 3],
 [22, 3],
 [3, 7],
 [1, 21],
 [10, 4],
 [19, 3],
 [11, 8],
 [22, 5],
 [18, 2],
 [11, 7],
 [15, 40],
 [11, 1],
 [19, 10],
 [23, 1],
 [14, 22],
 [16, 4],
 [21, 4],
 [17, 15],
 [4, 3],
 [3, 3],
 [16, 5],
 [22, 5],
 [10, 3],
 [0, 1],
 [20, 4],
 [20, 6],
 [4, 13],
 [21, 1],
 [1, 3],
 [4, 62],
 [19, 6],
 [16, 3],
 [5, 9],
 [19, 43],
 [16, 7],
 [11, 1],
 [21, 2],
 [12, 6],
 [0, 1],
 [17, 23],
 [9, 2],
 [3, 2],
 [22, 2],
 [2, 2],
 [8, 78],
 [11, 4],
 [8, 3],
 [19, 4],
 [8, 4],
 [15, 128],
 [21, 6],
 [3, 32],
 [19, 12],
 [17, 7],
 [21, 2],
 [10, 3],
 [11, 3],
 [12, 3],
 [0, 1],
 [19, 4],
 [18, 11],
 [18, 7],
 [5, 14],
 [18, 4],
 [17, 2],
 [20, 7],
 [12, 2],
 [23, 18],
 [20, 1],
 [1, 4],
 [13, 5],
 [14, 1],
 [14, 2],
 [7, 1],
 [19, 1],
 [10, 2],
 [13, 2],
 [10, 2],
 [11, 15],
 [8, 9],
 [21, 3],
 [12, 2],
 [19, 7],
 [20, 2],
 [19, 2],
 [22, 4],
 [6, 6],
 [6, 8],
 [23, 7],
 [23, 65],
 [6, 10],
 [0, 2],
 [0, 14],
 [6, 50],
 [21, 2],
 [20, 4],
 [16, 1],
 [7, 12],
 [2, 2],
 [9, 4],
 [20, 2],
 [5, 3],
 [19, 7],
 [2, 1],
 [15, 14],
 [21, 520],
 [18, 7],
 [14, 3],
 [10, 1],
 [20, 40],
 [2, 31],
 [18, 9],
 [15, 1],
 [14, 94],
 [4, 2],
 [20, 3],
 [15, 118],
 [2, 2],
 [19, 3],
 [18, 7],
 [13, 6],
 [8, 1],
 [2, 2],
 [17, 3],
 [21, 2],
 [8, 12],
 [10, 1],
 [12, 5],
 [22, 6],
 [18, 3],
 [21, 1],
 [18, 27],
 [14, 5],
 [0, 1],
 [17, 1],
 [16, 8],
 [21, 7],
 [21, 2],
 [8, 2],
 [7, 53],
 [15, 9],
 [22, 7],
 [1, 2],
 [20, 477],
 [19, 3],
 [15, 111],
 [4, 18],
 [13, 4],
 [4, 2],
 [12, 17],
 [3, 1],
 [2, 6],
 [21, 1],
 [3, 31],
 [14, 11],
 [16, 1],
 [23, 7],
 [1, 1],
 [14, 1],
 [17, 96],
 [10, 1],
 [17, 5],
 [16, 2],
 [15, 1],
 [12, 7],
 [17, 6],
 [5, 1],
 [18, 3],
 [22, 2],
 [9, 1],
 [7, 20],
 [10, 4],
 [0, 4],
 [3, 15],
 [3, 12],
 [20, 4],
 [4, 2],
 [15, 6],
 [7, 2],
 [13, 1],
 [18, 10],
 [20, 5],
 [13, 3],
 [7, 2],
 [11, 128],
 [6, 1],
 [6, 2],
 [16, 1],
 [18, 11],
 [9, 4],
 [11, 3],
 [10, 10],
 [7, 5],
 [9, 7],
 [2, 7],
 [6, 14],
 [21, 1],
 [19, 6],
 [21, 9],
 [17, 135],
 [23, 9],
 [13, 7],
 [10, 1],
 [21, 5],
 [13, 9],
 [12, 9],
 [21, 1],
 [13, 14],
 [15, 16],
 [3, 2],
 [15, 1],
 [19, 37],
 [3, 1],
 [12, 1],
 [10, 4],
 [16, 1],
 [12, 2],
 [18, 1],
 [2, 101],
 [14, 2],
 [19, 52],
 [1, 2],
 [19, 5],
 [10, 12],
 [7, 11],
 [21, 5],
 [9, 3],
 [18, 3],
 [8, 1],
 [16, 4],
 [20, 2],
 [5, 7],
 [19, 3],
 [22, 13],
 [3, 20],
 [14, 3],
 [8, 45],
 [15, 1],
 [19, 6],
 [4, 4],
 [20, 4],
 [17, 3],
 [14, 1],
 [21, 17],
 [21, 2],
 [16, 3],
 [0, 4],
 [20, 2],
 [0, 3],
 [16, 10],
 [16, 2],
 [10, 50],
 [17, 47],
 [9, 1],
 [7, 2],
 [17, 5],
 [5, 1],
 [14, 28],
 [18, 1],
 [5, 3],
 [11, 1],
 [15, 22],
 [21, 41],
 [17, 1],
 [0, 1],
 [16, 1],
 [23, 4],
 [14, 1],
 [0, 10],
 [15, 5],
 [22, 3],
 [21, 147],
 [15, 1],
 [20, 1],
 [14, 12],
 [19, 5],
 [17, 2],
 [20, 3],
 [11, 3],
 [20, 2],
 [0, 4],
 [13, 3],
 [12, 10],
 [17, 5],
 [15, 9],
 [12, 2],
 [11, 6],
 [13, 6],
 [0, 3],
 [15, 3],
 [4, 2],
 [11, 2],
 [7, 3],
 [23, 8],
 [15, 4],
 [2, 4],
 [22, 4],
 [15, 144],
 [23, 6],
 [18, 11],
 [23, 9],
 [21, 1],
 [19, 4],
 [23, 6],
 [11, 3],
 [21, 131],
 [15, 1],
 [17, 1],
 [2, 6],
 [5, 4],
 [16, 16],
 [17, 4],
 [8, 2],
 [17, 3],
 [20, 2],
 [5, 2],
 [10, 61],
 [13, 31],
 [0, 3],
 [17, 2],
 [13, 2],
 [12, 5],
 [19, 1],
 [4, 11],
 [17, 2],
 [14, 3],
 [6, 2],
 [14, 1],
 [4, 12],
 [21, 3],
 [2, 7],
 [18, 1],
 [3, 4],
 [12, 1],
 [14, 1],
 [0, 3],
 [1, 2],
 [13, 6],
 [5, 2],
 [20, 3],
 [21, 4],
 [18, 1],
 [21, 10],
 [15, 8],
 [7, 8],
 [13, 1],
 [20, 7],
 [18, 34],
 [11, 10],
 [11, 1],
 [12, 43],
 [12, 9],
 [12, 4],
 [10, 1],
 [14, 1],
 [11, 3],
 [2, 25],
 [10, 1],
 [21, 2],
 [7, 9],
 [14, 190],
 [16, 11],
 [20, 4],
 [21, 9],
 [14, 1],
 [13, 1],
 [4, 2],
 [16, 6],
 [22, 2],
 [15, 1],
 [19, 11],
 [1, 3],
 [3, 16],
 [9, 1],
 [2, 1],
 [19, 1],
 [17, 1],
 [18, 7],
 [6, 21],
 [12, 2],
 [16, 35],
 [19, 4],
 [11, 2],
 [5, 16],
 [7, 8],
 [14, 1],
 [13, 2],
 [23, 5],
 [2, 8],
 [3, 33],
 [2, 8],
 [4, 10],
 [22, 1],
 [17, 2],
 [21, 2],
 [16, 5],
 [16, 1],
 [16, 5],
 [18, 383],
 ...]

In [19]:
for hour, comment in new_list:
    if hour not in counts_by_hour:
        counts_by_hour[hour] = 1
        comments_by_hour[hour] = comment
    else:
        counts_by_hour[hour]+=1
        comments_by_hour[hour]+=comment

In [20]:
counts_by_hour

{9: 45,
 13: 85,
 10: 59,
 14: 107,
 16: 108,
 23: 68,
 12: 73,
 17: 100,
 15: 116,
 21: 109,
 20: 80,
 2: 58,
 18: 109,
 3: 54,
 5: 46,
 19: 110,
 1: 60,
 22: 71,
 8: 48,
 4: 47,
 0: 55,
 6: 44,
 7: 34,
 11: 58}

In [21]:
comments_by_hour

{9: 251,
 13: 1253,
 10: 793,
 14: 1416,
 16: 1814,
 23: 543,
 12: 687,
 17: 1146,
 15: 4477,
 21: 1745,
 20: 1722,
 2: 1381,
 18: 1439,
 3: 421,
 5: 464,
 19: 1188,
 1: 683,
 22: 479,
 8: 492,
 4: 337,
 0: 447,
 6: 397,
 7: 267,
 11: 641}

In [22]:
avg_by_hour = []
for hour in comments_by_hour:
    avg_by_hour.append([hour, comments_by_hour[hour]/counts_by_hour[hour]])

In [23]:
avg_by_hour

[[9, 5.5777777777777775],
 [13, 14.741176470588234],
 [10, 13.440677966101696],
 [14, 13.233644859813085],
 [16, 16.796296296296298],
 [23, 7.985294117647059],
 [12, 9.41095890410959],
 [17, 11.46],
 [15, 38.5948275862069],
 [21, 16.009174311926607],
 [20, 21.525],
 [2, 23.810344827586206],
 [18, 13.20183486238532],
 [3, 7.796296296296297],
 [5, 10.08695652173913],
 [19, 10.8],
 [1, 11.383333333333333],
 [22, 6.746478873239437],
 [8, 10.25],
 [4, 7.170212765957447],
 [0, 8.127272727272727],
 [6, 9.022727272727273],
 [7, 7.852941176470588],
 [11, 11.051724137931034]]

In [ ]:
swap_avg_by_hour = []

In [30]:
df_new = pd.DataFrame(avg_by_hour, columns = ['hours', 'avg_num_comments'])

In [34]:
df_new.sort_values('avg_num_comments', ascending=False, inplace=True)

In [39]:
df_new.reset_index(drop=True, inplace=True)

In [40]:
df_new

    hours  avg_num_comments
0      15         38.594828
1       2         23.810345
2      20         21.525000
3      16         16.796296
4      21         16.009174
5      13         14.741176
6      10         13.440678
7      14         13.233645
8      18         13.201835
9      17         11.460000
10      1         11.383333
11     11         11.051724
12     19         10.800000
13      8         10.250000
14      5         10.086957
15     12          9.410959
16      6          9.022727
17      0          8.127273
18     23          7.985294
19      7          7.852941
20      3          7.796296
21      4          7.170213
22     22          6.746479
23      9          5.577778